In [1]:
import txt2speech_test
from IPython.display import Audio

# text_vietnamese = [
#     "Nhìn này, tôi biết điều này nghe có vẻ điên rồ, nhưng bạn của tôi Ben vừa mới chuyển đến căn hộ cũ kiểu nghệ thuật này ở trung tâm thành phố",
#     "Nó có sự quyến rũ mang đậm phong cách cổ điển - tấm nền giấy dán bong tróc với những họa tiết hoa tàn phai kể lể những câu chuyện đã bị lãng quên",
#     "Sàn gỗ mục nát kêu rên mỗi khi bước chân đặt lên như những linh hồn của những người thuê không yên",
#     "Và đỉnh điểm của tất cả: cái thang máy cũ kỹ kêu rên hơn là trượt",
#     "Cảm giác như nó đang sắp từ bỏ linh hồn mỗi lần lên cao, tiếng kêu gỉ sét vang vọng qua những hành lang bụi bặm."
# ]

text_vietnamese = [
    "Hôm qua Ben nhắn tin cho tôi trong hoảng loạn",
    "Anh ấy bị kẹt trong thang máy giữa các tầng",
    "Không phải là vấn đề lớn... đúng không... Chuyện này có thể xảy ra với bất kỳ ai mà",
    "Nhưng đây là phần đáng lo ngại: có một Tầng thứ mười ba không có trên bảng nút bấm",
    "Chỗ ấy chỉ là một khoảng trống như thể thách thức bạn nhấn cái nút không tồn tại ấy"
]

output, model = txt2speech_test.txt2speech(text_vietnamese)


Some weights of the model checkpoint at facebook/mms-tts-vie were not used when initializing VitsModel: ['flow.flows.0.wavenet.in_layers.0.weight_g', 'flow.flows.0.wavenet.in_layers.0.weight_v', 'flow.flows.0.wavenet.in_layers.1.weight_g', 'flow.flows.0.wavenet.in_layers.1.weight_v', 'flow.flows.0.wavenet.in_layers.2.weight_g', 'flow.flows.0.wavenet.in_layers.2.weight_v', 'flow.flows.0.wavenet.in_layers.3.weight_g', 'flow.flows.0.wavenet.in_layers.3.weight_v', 'flow.flows.0.wavenet.res_skip_layers.0.weight_g', 'flow.flows.0.wavenet.res_skip_layers.0.weight_v', 'flow.flows.0.wavenet.res_skip_layers.1.weight_g', 'flow.flows.0.wavenet.res_skip_layers.1.weight_v', 'flow.flows.0.wavenet.res_skip_layers.2.weight_g', 'flow.flows.0.wavenet.res_skip_layers.2.weight_v', 'flow.flows.0.wavenet.res_skip_layers.3.weight_g', 'flow.flows.0.wavenet.res_skip_layers.3.weight_v', 'flow.flows.1.wavenet.in_layers.0.weight_g', 'flow.flows.1.wavenet.in_layers.0.weight_v', 'flow.flows.1.wavenet.in_layers.1.wei

tensor([[ 5.2154e-05,  8.9913e-05,  4.0742e-05,  ...,  3.4256e-03,
          2.8313e-03,  2.8511e-03],
        [ 8.5721e-06,  5.6012e-05,  2.0993e-05,  ...,  3.4256e-03,
          2.8313e-03,  2.8511e-03],
        [-2.3651e-04, -2.2223e-04, -1.9347e-04,  ...,  3.4256e-03,
          2.8313e-03,  2.8511e-03],
        [-8.0819e-05, -9.0300e-05, -9.4632e-05,  ...,  8.6878e-05,
          4.1198e-05,  2.0556e-04],
        [ 5.4144e-05,  9.5236e-05,  4.8443e-05,  ...,  3.4256e-03,
          2.8313e-03,  2.8511e-03]], device='cuda:0')


In [2]:
print(output.get_device())
# output = output.cpu()
output

-1


tensor([[ 5.2154e-05,  8.9913e-05,  4.0742e-05,  ...,  3.4256e-03,
          2.8313e-03,  2.8511e-03],
        [ 8.5721e-06,  5.6012e-05,  2.0993e-05,  ...,  3.4256e-03,
          2.8313e-03,  2.8511e-03],
        [-2.3651e-04, -2.2223e-04, -1.9347e-04,  ...,  3.4256e-03,
          2.8313e-03,  2.8511e-03],
        [-8.0819e-05, -9.0300e-05, -9.4632e-05,  ...,  8.6878e-05,
          4.1198e-05,  2.0556e-04],
        [ 5.4144e-05,  9.5236e-05,  4.8443e-05,  ...,  3.4256e-03,
          2.8313e-03,  2.8511e-03]])

In [3]:
import IPython
import noisereduce as nr

for out in output: 
    # out = nr.reduce_noise(y=out, sr=model.config.sampling_rate, stationary=True)
    IPython.display.display(Audio(out, rate=model.config.sampling_rate))

In [4]:
# numpy_out = output.numpy()
# import scipy
# counter = 0
# for out in numpy_out:
#     counter +=1  
#     scipy.io.wavfile.write(f"sound_{counter}.wav", rate=model.config.sampling_rate, data=out)

In [5]:
output[3]

tensor([-5.8340e-05,  2.2351e-05,  5.7200e-05,  ...,  3.4257e-03,
         2.8313e-03,  2.8511e-03])

In [3]:
model.config

VitsConfig {
  "_name_or_path": "facebook/mms-tts-vie",
  "activation_dropout": 0.1,
  "architectures": [
    "VitsModel"
  ],
  "attention_dropout": 0.1,
  "depth_separable_channels": 2,
  "depth_separable_num_layers": 3,
  "duration_predictor_dropout": 0.5,
  "duration_predictor_filter_channels": 256,
  "duration_predictor_flow_bins": 10,
  "duration_predictor_kernel_size": 3,
  "duration_predictor_num_flows": 4,
  "duration_predictor_tail_bound": 5.0,
  "ffn_dim": 768,
  "ffn_kernel_size": 3,
  "flow_size": 192,
  "hidden_act": "relu",
  "hidden_dropout": 0.1,
  "hidden_size": 192,
  "initializer_range": 0.02,
  "layer_norm_eps": 1e-05,
  "layerdrop": 0.1,
  "leaky_relu_slope": 0.1,
  "model_type": "vits",
  "noise_scale": 0.667,
  "noise_scale_duration": 0.8,
  "num_attention_heads": 2,
  "num_hidden_layers": 6,
  "num_speakers": 0,
  "posterior_encoder_num_wavenet_layers": 16,
  "prior_encoder_num_flows": 4,
  "prior_encoder_num_wavenet_layers": 4,
  "resblock_dilation_sizes": [
 